sudo: false
env:
  matrix:
  - BROWSER=chromium EXT=zip
  - BROWSER=firefox EXT=xpi
  - BROWSER=webext EXT=xpi
script: ./tools/make-${BROWSER}.sh all
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: eQgPAHH6PKu2dLK+NafxwLl66t0cyW5x5NZFquOwsNMal5nsfof7lyXj2F0Q0vUpGeI21MOipBI8UGv5oXPoiXnr0fhEbEBz65C9vypK61WkDCQVGVeZVNGQwSXUm6gD2EzpPgTCIs52+7dKCDJ3stXzdimOiOTYs4WMNKKarFM=
  file: dist/build/uMatrix.${BROWSER}.${EXT}
  skip_cleanup: true
  on:
    repo: gorhill/uMatrix
    tags: true
    all_branches: true
